apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sanitytests.sanity.test.com
spec:
  group: sanity.test.com
  names:
    kind: SanityTest
    listKind: SanityTestList
    plural: sanitytests
    singular: sanitytest
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
